# galaxy.yml for jcook3701.flatpak
#
# Copyright (c) 2026, Jared Cook
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <www.gnu.org>.
#
---
namespace: "jcook3701"
name: "flatpak"
version: "1.0.1"
authors:
  - "Jared Cook @jcook3701"
license:
  - GPL-3.0
readme: ./README.md
description: >
  Ansible installer for flatpak packages.

tags:
  - lab
  - homelab
  - automation
  - infrastructure

dependencies:
  jcook3701.pkgs: "*"
  jcook3701.utils: "*"
  ansible.builtin: "*"
  community.general: ">=8.0.0"

build_ignore:
  - .gitignore
  - .github/
  - tests/
  - docs/
  - scripts/
  - .venv/

repository: >-
  https://github.com/jcook3701/\
  jcook3701.jcook3701.flatpak
documentation: >-
  https://github.com/jcook3701/\
  jcook3701.jcook3701.flatpak/blob/main/README.md
homepage: >-
  https://github.com/jcook3701/\
  jcook3701.jcook3701.flatpak
issues: >-
  https://github.com/jcook3701/\
  jcook3701.jcook3701.flatpak/issues
...
