# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Manage Authenticator flatpak
  community.general.flatpak:
    name: com.belmoussaoui.Authenticator
    state: "{{ authenticator_state | default('present') }}"
    remote: flathub
  when: ansible_facts.packages['flatpak'] is defined
