# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Manage Bottles flatpak
  community.general.flatpak:
    name: "{{ bottles_package }}"
    state: "{{ bottles_state | default('present') }}"
    remote: "{{ bottles_remote_name }}"
  when: ansible_facts.packages['flatpak'] is defined
