# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
localsend_state: present
localsend_package: org.localsend.localsend_app
localsend_remote_name: flathub
localsend_remote_url: https://flathub.org
